name: EBAC CI

on:
  push:
    branches: [ ci ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm start &
        env:
          CI: true
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install-command: npm install
          browser: chrome
          start: npm start
          command: npx cypress run --config-file cypress.config.js
      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report
