name: EBAC CI

on:
  push:
    branches: [ci]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - uses: actions/checkout@v2

      # Configuração do Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Iniciar o servidor e executar os testes do Cypress
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          install-command: npm install
          browser: chrome
          start: npm start
        env:
          CI: true

      # Gerar o relatório do mochawesome
      - name: Generate mochawesome report
        run: npm run cy:report

      # Publicar o relatório no GitHub Pages
      - name: Publish mochawesome Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report
